### ISSUE TITLE
Clustering error: Suggestion: increase n_points

### ISSUE THREAD

**Issue by Masilokwa-bantu** [3DFin/dendromatics#36]
Hello Dendromatics Developers,

Hope you are well today. I wanted to find out if there is an example.las point cloud that can be used to test the dendromatics library example.py. As I have run into  the error shown below and have followed the error prompt to increase the number of points (n_points) however this has not worked. 

 -Extracting 'candidate' stems...
Traceback (most recent call last):
  File "C:\Users\Vincent\PycharmProjects\dendromatics\examples\example.py", line 39, in <module>
    stripe_stems = dm.stripe.verticality_clustering(stripe, resolution_z=0.05, resolution_xy=0.05, n_points=1000000 )
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vincent\anaconda3\envs\dendromatics_test\Lib\site-packages\dendromatics\stripe.py", line 238, in verticality_clustering
    clust_stripe, t = verticality_clustering_iteration(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vincent\anaconda3\envs\dendromatics_test\Lib\site-packages\dendromatics\stripe.py", line 148, in verticality_clustering_iteration
    raise ValueError(
ValueError: Clusters were found, but they are too small to be considered potential stems using current settings. Suggestion: increase n points.

Process finished with exit code 1

Therefore, I wanted to find out if the was an example point cloud to test and see if the example.py file is working correctly before making any further changes to other params. Although if there is a way that this error can be fixed. I incrementally increased n_points from the default 1000 by a factor of 10 each time until i reached 1million and given that the error still occurs after the number of points are exceed I was a bit confused. 

Any assistance that you can provide is greatly appreciated.

**Comment by stefp** [comment]
Hi, I agree. I have been testing it but get the same error. 

It would be great to have a small working example of a test point cloud for which example.py works.
